// Action Types
export const CREATE_GUEST_REQUEST = 'CREATE_GUESTS_REQUEST';
export const CREATE_GUEST_SUCCESS = 'CREATE_GUESTS_SUCCESS';
export const CREATE_GUEST_ERROR = 'CREATE_GUESTS_ERROR';

export const UPDATE_GUEST_REQUEST = 'UPDATE_GUESTS_REQUEST';
export const UPDATE_GUEST_SUCCESS = 'UPDATE_GUESTS_SUCCESS';
export const UPDATE_GUEST_ERROR = 'UPDATE_GUESTS_ERROR';

export const DELETE_GUEST_REQUEST = 'DELETE_GUESTS_REQUEST';
export const DELETE_GUEST_SUCCESS = 'DELETE_GUESTS_SUCCESS';
export const DELETE_GUEST_ERROR = 'DELETE_GUESTS_ERROR';
