export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_ERROR = 'LOGOUT_ERROR';

export const GENERATE_APIKEY_REQUEST = 'GENERATE_APIKEY_REQUEST';
export const GENERATE_APIKEY_SUCCESS = 'GENERATE_APIKEY_SUCCESS';
export const GENERATE_APIKEY_ERROR = 'GENERATE_APIKEY_ERROR';

